version: '3.1'

services:
  mongodb:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .mongodb_env
    volumes:
      - ${USER_HOME}/workspace/health-mongodb:/data/db
